/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{svelte,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-surface-variant": "#43474e",
              "on-secondary-fixed": "#261900",
              "secondary": "#775a19",
              "tertiary-container": "#213c1b",
              "inverse-on-surface": "#eff1f3",
              "surface-dim": "#d8dadc",
              "inverse-surface": "#2d3133",
              "primary-container": "#1a365d",
              "secondary-fixed": "#ffdea5",
              "surface-container-lowest": "#ffffff",
              "on-error": "#ffffff",
              "on-tertiary": "#ffffff",
              "secondary-fixed-dim": "#e9c176",
              "surface-tint": "#455f88",
              "outline-variant": "#c4c6cf",
              "tertiary-fixed-dim": "#afd0a1",
              "on-primary": "#ffffff",
              "tertiary-fixed": "#caecbc",
              "secondary-container": "#fed488",
              "error-container": "#ffdad6",
              "on-error-container": "#93000a",
              "on-background": "#191c1e",
              "on-primary-fixed": "#001b3c",
              "surface-container-high": "#e6e8ea",
              "on-primary-container": "#86a0cd",
              "on-tertiary-fixed-variant": "#324e2a",
              "surface-container-low": "#f2f4f6",
              "outline": "#74777f",
              "on-primary-fixed-variant": "#2d476f",
              "surface-variant": "#e0e3e5",
              "on-tertiary-container": "#88a77c",
              "on-tertiary-fixed": "#062104",
              "tertiary": "#0b2607",
              "primary": "#002045",
              "inverse-primary": "#adc7f7",
              "surface": "#f7f9fb",
              "surface-container": "#eceef0",
              "surface-bright": "#f7f9fb",
              "error": "#ba1a1a",
              "on-secondary": "#ffffff",
              "on-secondary-container": "#785a1a",
              "on-secondary-fixed-variant": "#5d4201",
              "background": "#f7f9fb",
              "surface-container-highest": "#e0e3e5",
              "on-surface": "#191c1e",
              "primary-fixed": "#d6e3ff",
              "primary-fixed-dim": "#adc7f7"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "lg": "2.5rem",
              "xl": "4rem",
              "base": "0.5rem",
              "sm": "0.75rem",
              "container-max": "75rem",
              "gutter": "1.5rem",
              "md": "1.5rem",
              "xs": "0.25rem"
      },
      "fontFamily": {
              "label-md": ["Inter"],
              "headline-lg": ["Inter"],
              "headline-md": ["Inter"],
              "label-sm": ["Inter"],
              "headline-lg-mobile": ["Inter"],
              "display-lg": ["Inter"],
              "title-lg": ["Inter"],
              "body-md": ["Inter"],
              "body-lg": ["Inter"]
      },
      "fontSize": {
              "label-md": ["0.875rem", {"lineHeight": "1.25rem", "letterSpacing": "0.01em", "fontWeight": "500"}],
              "headline-lg": ["2rem", {"lineHeight": "2.5rem", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "headline-md": ["1.5rem", {"lineHeight": "2rem", "fontWeight": "600"}],
              "label-sm": ["0.75rem", {"lineHeight": "1rem", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "headline-lg-mobile": ["1.5rem", {"lineHeight": "2rem", "fontWeight": "600"}],
              "display-lg": ["3rem", {"lineHeight": "3.5rem", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "title-lg": ["1.25rem", {"lineHeight": "1.75rem", "fontWeight": "600"}],
              "body-md": ["1rem", {"lineHeight": "1.5rem", "fontWeight": "400"}],
              "body-lg": ["1.125rem", {"lineHeight": "1.75rem", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}