/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{svelte,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#dae2fd",
        "tertiary-container": "#271901",
        "on-secondary-fixed": "#001a42",
        "inverse-surface": "#213145",
        "background": "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "on-primary": "#ffffff",
        "surface-container": "#e5eeff",
        "secondary-container": "#2170e4",
        "secondary": "#0058be",
        "on-secondary-fixed-variant": "#004395",
        "surface-dim": "#cbdbf5",
        "tertiary": "#000000",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "primary": "#000000",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#adc6ff",
        "tertiary-fixed-dim": "#dec29a",
        "on-tertiary": "#ffffff",
        "on-background": "#0b1c30",
        "on-tertiary-fixed-variant": "#574425",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary-container": "#7c839b",
        "surface-bright": "#f8f9ff",
        "on-surface": "#0b1c30",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "primary-fixed-dim": "#bec6e0",
        "secondary-fixed": "#d8e2ff",
        "outline-variant": "#c6c6cd",
        "primary-container": "#131b2e",
        "on-error-container": "#93000a",
        "surface": "#f8f9ff",
        "on-primary-fixed": "#131b2e",
        "on-tertiary-container": "#98805d",
        "surface-variant": "#d3e4fe",
        "on-secondary": "#ffffff",
        "inverse-primary": "#bec6e0",
        "tertiary-fixed": "#fcdeb5",
        "on-tertiary-fixed": "#271901",
        "surface-tint": "#565e74",
        "on-surface-variant": "#45464d",
        "on-secondary-container": "#fefcff",
        "outline": "#76777d",
        "inverse-on-surface": "#eaf1ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "data-mono": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "headline-lg": ["Hanken Grotesk"],
        "label-caps": ["Inter"],
        "headline-md": ["Hanken Grotesk"],
        "body-lg": ["Inter"]
      }
    },
  },
  plugins: [],
}
