CREATE TABLE kb_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_favorite_user FOREIGN KEY (user_id) REFERENCES kb_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_favorite_doc FOREIGN KEY (document_id) REFERENCES kb_documents(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_document UNIQUE (user_id, document_id)
);

CREATE TABLE kb_saved_queries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    query_text VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_saved_query_user FOREIGN KEY (user_id) REFERENCES kb_users(id) ON DELETE CASCADE
);
