CREATE TABLE kb_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kb_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(255),
    author_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_kb_doc_author FOREIGN KEY (author_id) REFERENCES kb_users(id)
);

CREATE TABLE kb_document_tags (
    document_id BIGINT NOT NULL,
    tag_name VARCHAR(100) NOT NULL,
    PRIMARY KEY (document_id, tag_name),
    CONSTRAINT fk_kb_tag_doc FOREIGN KEY (document_id) REFERENCES kb_documents(id) ON DELETE CASCADE
);

CREATE TABLE kb_document_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    version_number INT NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_type VARCHAR(50),
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_kb_version_doc FOREIGN KEY (document_id) REFERENCES kb_documents(id),
    CONSTRAINT fk_kb_version_user FOREIGN KEY (created_by) REFERENCES kb_users(id)
);

CREATE TABLE kb_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    action VARCHAR(255) NOT NULL,
    target_entity VARCHAR(255) NOT NULL,
    target_id BIGINT,
    details TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_kb_audit_user FOREIGN KEY (user_id) REFERENCES kb_users(id)
);
