CREATE TABLE kb_document_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_kb_comment_doc FOREIGN KEY (document_id) REFERENCES kb_documents(id) ON DELETE CASCADE,
    CONSTRAINT fk_kb_comment_user FOREIGN KEY (author_id) REFERENCES kb_users(id) ON DELETE CASCADE
);
