-- V20260730231112325__create_user_permissions_and_sync.sql
-- Create table for storing local user permissions derived from synced EIOS roles.

CREATE TABLE local_user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    internal_eios_identifier VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_permission UNIQUE (user_id, internal_eios_identifier)
);
